model = "F5-TTS"
pages = 3
toml_Folder = "TTS/src/f5_tts/infer/examples/basic"
ref_audio = "TTS/src/f5_tts/infer/examples/basic/basic_ref_zh.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = "对，这就是我，万人敬仰的太乙真人。"
gen_text = "哪吒，你妈喊你回家吃饭了。"
# File with text to generate. Ignores the text above.
gen_file = ""
speed = 1.0
remove_silence = false
output_dir = "Wav/examples"
output_name = "infer_cli_basic.wav"
